<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_addToCart_item</name>
   <tag></tag>
   <elementGuidId>a339f1ff-fa3a-4ab6-be5f-a30a9af10e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='${id_item}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='${id_item}']</value>
      <webElementGuid>1c5d8d37-aa4f-4cc8-a52c-1053f9377a59</webElementGuid>
   </webElementProperties>
</WebElementEntity>
