<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_cart</name>
   <tag></tag>
   <elementGuidId>a145f1f4-7a3b-4077-b57e-a1efa33044f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@class='shopping_cart_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@class='shopping_cart_link']</value>
      <webElementGuid>aba9b1e5-76ff-4438-b8e7-33582e9861a2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
