<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_yourCart</name>
   <tag></tag>
   <elementGuidId>d0e82d3a-abea-41ae-b077-6e6cb37ccede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@data-test=&quot;title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@data-test=&quot;title&quot;]</value>
      <webElementGuid>365dcc81-ffab-4bf8-b706-5de3e10de199</webElementGuid>
   </webElementProperties>
</WebElementEntity>
