<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_checkoutPage</name>
   <tag></tag>
   <elementGuidId>24f3ad97-9097-4c01-a69b-03afc582bf95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@data-test=&quot;title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@data-test=&quot;title&quot;]</value>
      <webElementGuid>35045501-3a43-4d43-8f29-30b471d59b8b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
