<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_products</name>
   <tag></tag>
   <elementGuidId>b228aa65-90ec-41c5-bdae-cc4d9d72a783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Products')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Products')]</value>
      <webElementGuid>ef8fe7b6-a001-4d88-ad91-9f8ea2de9709</webElementGuid>
   </webElementProperties>
</WebElementEntity>
