<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_inventoryPrice</name>
   <tag></tag>
   <elementGuidId>a27b3603-ad7a-4280-859c-a18766325345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-test=&quot;inventory-item-price&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-test=&quot;inventory-item-price&quot;]</value>
      <webElementGuid>872df7e1-55a9-4722-b003-21b16b1d907e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
