<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_titlePage</name>
   <tag></tag>
   <elementGuidId>d2549e19-c554-4b31-8eab-d2957a9539b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@data-test=&quot;title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@data-test=&quot;title&quot;]</value>
      <webElementGuid>0cf84a0d-6a39-46be-9831-14154a6311f4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
